### ISSUE TITLE
This plugin doesn't work on gedit 3.30

### ISSUE THREAD

**Issue by kiwiheretic** [lwindolf/gedit-pluginbrowser#3]

**Comment by lwindolf** [comment]
Cannot reproduce this with the 3.30.2 installation I'm running.

Can you provide some details on the problem? If something breaks you can see it on the console. Please start gedit from a terminal and post any exceptions here.

**Comment by kiwiheretic** [comment]
I got this output from conole.

main.go:224: cannot change mount namespace of snap "gedit" according to change mount (/snap/gtk-common-themes/818/share/icons/Suru /snap/gedit/66/data-dir/icons/Suru none bind,ro 0 0): cannot use "/snap/gtk-common-themes/818/share/icons/Suru" as bind-mount source: not a directory
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected

(gedit:9177): gspell-WARNING **: 20:17:21.910: iso_639.xml: Failed to open file “/usr/share/xml/iso-codes/iso_639.xml”: open() failed: No such file or directory

(gedit:9177): gspell-WARNING **: 20:17:21.910: iso_3166.xml: Failed to open file “/usr/share/xml/iso-codes/iso_3166.xml”: open() failed: No such file or directory

As you can see from below I have installed it in the ~/.local directory
![gedit-plugins-installed](https://user-images.githubusercontent.com/3701543/52530877-70e32700-2d71-11e9-8bb3-1f49e9b8708f.png)

**Comment by lwindolf** [comment]
Doesn't look like any plugin errors to me. Some questions:

1. Does gedit show the plugin as activated or with errors in the preferences/plugins list?
2. Do you see the menu entry "Install Plugins" in the main menu?

**Comment by kiwiheretic** [comment]
gedit doesn't show the plugin at all in the preferences window.

![install-plugin-missing](https://user-images.githubusercontent.com/3701543/54469479-5df2c500-47fd-11e9-97e6-a4904d8d3b91.png)

**Comment by seasonedgeek** [comment]
Happy Day! Plugin works on gedit 3.28.1!

**Comment by lwindolf** [comment]
Also works fine with recent Ubuntu packaged 3.32 version

**Comment by lwindolf** [comment]
@kiwiheretic I recently learned this is happening when running inside sandboxes like with snap/flatpak.

If the sandbox is missing git then the plugin cannot download stuff and silently fails. I will add a check for this.

**Comment by lwindolf** [comment]
Added warning dialog to code.
