### ISSUE TITLE
The 'python3' plugin loader has not been enabled

### ISSUE THREAD

**Issue by ndg63276** [lwindolf/gedit-pluginbrowser#4]
I get this error when trying to enable the plugin:
```
(gedit:27841): libpeas-WARNING **: 12:21:29.246: The 'python3' plugin loader has not been enabled
```
Any ideas?

**Comment by lwindolf** [comment]
AFAIK this can happen if you use an out-dated libpeas library (e.g. one being compiled without python3 support).

**Comment by ndg63276** [comment]
Sounds about right. I'm at work, on a managed system though, so can't update it I don't think.
