### ISSUE TITLE
Doesn't work on Gedit 3.20.1 on Windows 10.

### ISSUE THREAD

**Issue by aks2161989** [lwindolf/gedit-pluginbrowser#5]
Cannot install the plugin on Gedit 3.20.1 on Windows 10. cmd.exe shows the following message:

```
(gedit.exe:11100): libpeas-WARNING **: Failed to run internal Python hook 'load':
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "peas-python-internal.py", line 71, in call
SystemError: <built-in function getattr> returned a result with an error set

(gedit.exe:11100): libpeas-WARNING **: Error loading plugin 'plugininstaller'
```
What could be the problem?

**Edit:** I can **successfully** activate this plugin ONLY if the activation of another plugin fails before this. The activation of the previous plugin must fail with the same error message shown above. Fresh activation of gedit-plugininstaller or installation after **successful** installation of another plugin results in failure of activation.

Plugin does **not** work despite successful installation. On clicking "preferences" option of the plugin, cmd shows:

`(gedit.exe:8000): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed`

**Comment by lwindolf** [comment]
According to https://github.com/rbgirshick/py-faster-rcnn/issues/221 and https://github.com/thaines/helit/issues/8 this is caused by missing GObject Cairo bindings.

I have to admit though that I have no clue on how to install those on Windows :-(

**Comment by misaki-web** [comment]
All dependencies can be installed automatically if we use MSYS2: https://www.msys2.org

Example after installing MSYS2:

```
C:\msys64\mingw64.exe
pacman -Suy
pacman -S mingw-w64-x86_64-gedit mingw-w64-x86_64-gedit-plugins
C:\msys64\mingw64\bin\gedit.exe
```

Plugins copied in `C:\msys64\mingw64\lib\gedit\plugins` will be activable.

**Comment by lwindolf** [comment]
I've hinted on the MSYS2 installation instructions in the README!
