### ISSUE TITLE
reflow listed as Favorites and Favorites broken.

### ISSUE THREAD

**Issue by dentarthur** [lwindolf/gedit-pluginbrowser#6]
version 0.1.0 on Gnome gedit 3.32.2, Fedora Linux 5.2.17-200.fc30.x86_64

When listing All plugins available to install, "Favorites" is listed twice.

After installing both, the second instance is actually "reflow" in:

/home/admin/.local/share/gedit/plugins/

https://github.com/Quixotix/gedit-favorites 3.0 listed as not available in "Activate Plugins" with error message:

"Plugin loader 'python' was not found."

Reflow 2.0.0 also listed, and shown as activated.

I am guessing favorites.plugin should say Loader:python3 instead of 'python'.

But I am not familiar with anything and have not checked.

**Comment by lwindolf** [comment]
I've dropped the favourites plugin. It is Python2 only and probably won't work on newer distros.
